Repository Kumiho1/lubimovka, pull requests merged in 2022-10, with the labels that each got.

#59 feat: marked up section for desktop, checked with Pixel Perfect
  .gitignore
  blocks/cooperation/__asterisk/cooperation__asterisk.css
  blocks/cooperation/__link/cooperation__link.css
  blocks/cooperation/__paragraph/cooperation__paragraph.css
  blocks/cooperation/__text/cooperation__text.css
  blocks/cooperation/__title/cooperation__title.css
  blocks/cooperation/cooperation.css
  blocks/section-text/section-text.css
  index.html
  pages/index.css
Labels: enhancement

#69 Feature/perfomances
  blocks/link/__arrow-image/link__arrow-image.css
  blocks/link/link.css
  blocks/page/page.css
  blocks/perfomance-card/__author/perfomance-card__author.css
  blocks/perfomance-card/__authors/perfomance-card__authors.css
  blocks/perfomance-card/__date/perfomance-card__date.css
  blocks/perfomance-card/__datetime/perfomance-card__datetime.css
  blocks/perfomance-card/__image/perfomance-card__image.css
  blocks/perfomance-card/__info/perfomance-card__info.css
  blocks/perfomance-card/__link/perfomance-card__link.css
  blocks/perfomance-card/__links/perfomance-card__links.css
  blocks/perfomance-card/__paragraph/perfomance-card__paragraph.css
  blocks/perfomance-card/__title/perfomance-card__title.css
  blocks/perfomance-card/perfomance-card.css
  blocks/perfomances/__container/_inline-content/perfomances__container_inline-content.css
  blocks/perfomances/__container/perfomances__container.css
  blocks/perfomances/__item/perfomances__item.css
  blocks/perfomances/__list/_qty/perfomances__list_qty_two.css
  blocks/perfomances/__list/perfomances__list.css
  blocks/perfomances/perfomances.css
  blocks/section-title/_place/section-title_place_perfomances-inline-container.css
  blocks/section-title/_place/section-title_place_perfomances.css
  gitignore
  index.html
  pages/index.css
Labels: bug, enhancement

#71 feat: добавить верстку
  blocks/persons/__card/persons__card.css
  blocks/persons/__cards/persons__cards.css
  blocks/persons/__name/persons__name.css
  blocks/persons/__photo/persons__photo.css
  blocks/persons/__subtitle/persons__subtitle.css
  blocks/persons/__title/persons__title.css
  blocks/persons/persons.css
  index.html
  pages/index.css
Labels: enhancement

#76 сверстать подвал на десктоп без адаптива, проверить с PP
  blocks/cooperation/__paragraph/cooperation__paragraph.css
  blocks/cooperation/cooperation.css
  blocks/footer/__address-heading/footer__address-heading.css
  blocks/footer/__address-text/footer__address-text.css
  blocks/footer/__address/footer__address.css
  blocks/footer/__authors-designers/footer__authors-designers.css
  blocks/footer/__authors-developers/footer__authors-developers.css
  blocks/footer/__authors/footer__authors.css
  blocks/footer/__copyright/copyright.css
  blocks/footer/__fest-description/footer__fest-description.css
  blocks/footer/__icon-decorative/footer__icon-decorative.css
  blocks/footer/__link/footer__link.css
  blocks/footer/__links/_content/footer__links_content_partners.css
  blocks/footer/__links/footer__links.css
  blocks/footer/__logo/logo.css
  blocks/footer/__navigation/footer__navigation.css
  blocks/footer/__partners-heading/footer__partners-heading.css
  blocks/footer/__partners/footer__partners.css
  blocks/footer/__projects/footer__projects.css
  blocks/footer/__site-navigation/footer__site-navigation.css
  blocks/footer/__text/footer__text.css
  blocks/footer/footer.css
  images/logo-mosbrew.svg
  images/logo-prokhorov.svg
  images/logo-talk.svg
  index.html
  pages/index.css
Labels: bug, enhancement

#73 Feat/intro
  blocks/about/__title/about__title.css
  blocks/intro/__picture/intro__picture.css
  blocks/intro/__title/intro__title.css
  blocks/intro/intro.css
  gitignore
Labels: enhancement

#79 Hotfixes/validation
  blocks/footer/__address-text/footer__address-text.css
  blocks/footer/__address/footer__address.css
  index.html
Labels: bug

#114 feat: подготовить адаптив секции mobile; refactor: добавить auto перенос слов в текстовых блоках
  blocks/about/__text/about__text.css
  blocks/about/about.css
  blocks/cooperation/__link/cooperation__link.css
  blocks/cooperation/__text/cooperation__text.css
  blocks/cooperation/__title/cooperation__title.css
  blocks/cooperation/cooperation.css
  blocks/section-text/section-text.css
  blocks/section-title/section-title.css
  index.html
Labels: enhancement

#108 Feature/gallery
  blocks/buttons/__buttons.css
  blocks/buttons/__close-icon/buttons__close-icon.css
  blocks/buttons/__left-arrow/buttons__left-arrow.css
  blocks/buttons/__right-button/buttons__right-button.css
  blocks/gallery-photo/__item/gallery-photo__item.css
  blocks/gallery-photo/gallery-photo.css
  blocks/popup/__container-images/popup_container-images.css
  blocks/popup/__picture/popup__picture.css
  blocks/popup/_opened/popup_opened.css
  blocks/popup/popup.css
  images/Ellipse040.svg
  images/esc-white.png
  images/esc.png
  images/icon-esc.svg
  index.html
  pages/index.css
  scripts/popup.js
  scripts/video.js
Labels: enhancement

#120 feat: закончить адаптив для footer (мобайл и промежуточные брейки)
  blocks/cooperation/cooperation.css
  blocks/footer/__address-heading/footer__address-heading.css
  blocks/footer/__address-text/footer__address-text.css
  blocks/footer/__address/footer__address.css
  blocks/footer/__authors-designers-icon/footer__authors-designers-icon.css
  blocks/footer/__authors-developers/footer__authors-developers.css
  blocks/footer/__authors/footer__authors.css
  blocks/footer/__border/footer__border.css
  blocks/footer/__container/footer__container.css
  blocks/footer/__copyright/copyright.css
  blocks/footer/__icon-decorative/footer__icon-decorative.css
  blocks/footer/__links/_content/footer__links_content_partners.css
  blocks/footer/__links/footer__links.css
  blocks/footer/__logo/logo.css
  blocks/footer/__navigation/footer__navigation.css
  blocks/footer/__partner-logo/footer__partner-logo.css
  blocks/footer/__partners-heading/_display-visibility/footer__partners-heading_display-visibility_mobile.css
  blocks/footer/__partners-heading/footer__partners-heading.css
  blocks/footer/__partners/footer__partners.css
  blocks/footer/__projects/footer__projects.css
  blocks/footer/__text/_accent/footer__text_accent_underline.css
  blocks/footer/__text/footer__text.css
  blocks/footer/footer.css
  index.html
  pages/index.css
Labels: enhancement

#123 feature: сделать hover для ссылок в header в меню навигации
  blocks/header/__link/header__link.css
Labels: enhancement

#126 feat: добавить анимации элементов в header, gallery & footer
  blocks/cooperation/__link/cooperation__link.css
  blocks/footer/__link-authors/footer__link-authors.css
  blocks/footer/__link-logo/footer__link-logo.css
  blocks/footer/__link/footer__link.css
  blocks/footer/__text/_accent/footer__text_accent_underline.css
  blocks/gallery-photo/__container/gallery-photo__container.css
  blocks/gallery-photo/__item/gallery-photo__item.css
  blocks/header/__dagger-rect/header__dagger-rect.css
  blocks/header/__dagger/header__dagger.css
  blocks/header/__link/header__link.css
  blocks/header/__pay-link/header__pay-link.css
  index.html
  pages/index.css
Labels: enhancement
